openapi: 3.0.0
info:
  title: Mi API
  description: Una descripción de tu API.
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Servidor de desarrollo

paths:
  /auth:
    post:
      summary: Iniciar sesión
      requestBody:
        description: Datos de inicio de sesión
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Autenticación exitosa
          content:
            application/json:
              schema:
                type: string
        401:
          description: Error de autenticación

  /products:
    get:
      summary: Obtener lista de productos
      responses:
        200:
          description: Lista de productos
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        nombre:
                          type: string
        401:
          description: No autorizado

  /add_product:
    post:
      summary: Agregar un producto
      requestBody:
        description: Datos del nuevo producto
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
      responses:
        200:
          description: Producto agregado de forma asíncrona
